# Users

### GET
#### All
GET http://localhost:3001/users/

#### One
GET http://localhost:3001/users/1

### POST
POST http://localhost:3001/users/
Content-Type: application/json

{
    "name": "John New"
}

### PATCH
PATCH http://localhost:3001/users/1
Content-Type: application/json

{
    "name": "John One"
}

### DELETE
DELETE http://localhost:3001/users/1
Content-Type: application/json
